#===================================================================
# SwiftLint Configuration
# See https://realm.github.io/SwiftLint/rule-directory.html for rule details
#===================================================================

#-------------------------------------------------------------------
# Project-Specific Placeholders
#-------------------------------------------------------------------
# Replace the placeholders with values that match your project.

# Paths to include in linting
included:
  - TemplateApp/**/*.swift
  - TemplateAppTests/**/*.swift
  - TemplateAppUITests/**/*.swift
  - TemplateAppIntgTests/**/*.swift

#-------------------------------------------------------------------
# Analysis Targets
#-------------------------------------------------------------------
excluded:
  - .git
  - .build
  - DerivedData
  - .github
  - Carthage
  - build
  - xcbuild
  - "**/*.generated.swift"
  - "**/*.xcodeproj"

#-------------------------------------------------------------------
# Rule Configuration
#-------------------------------------------------------------------
disabled_rules:
  - trailing_whitespace # Allow trailing whitespace
  - line_length # Line length is customized separately
  - trailing_newline # Ignore trailing newline
  - trailing_comma # Disabled because controlled by SwiftFormat
  - missing_docs # Disable requirement for public API documentation
  - opening_brace # Disable opening brace placement rule
  - multiple_closures_with_trailing_closure # Allow trailing closure syntax when there are multiple closures
  - function_body_length # Disable function body length limit
  - type_body_length # Disable type body length limit

opt_in_rules:
  - empty_count # Use isEmpty instead of count == 0
  - force_unwrapping # Prohibit force unwrapping
  - sorted_imports # Sort imports
  - vertical_whitespace # Organize vertical whitespace
  - explicit_init # Explicitly describe all init
  - first_where # Prefer first(where:) over filter { ... }.first
  - toggle_bool # Prefer foo.toggle() over foo = !foo

analyzer_rules:
  - unused_declaration # Detect unused declarations
  - unused_import # Detect unused imports
  - explicit_self # Explicit self. when referencing properties or methods
  - redundant_nil_coalescing # Detect redundant ?? nil

#-------------------------------------------------------------------
# Individual Rule Settings
#-------------------------------------------------------------------

# File length limit
file_length:
  warning: 600
  error: 1000

# Cyclomatic complexity limit - calculated by total number of branches and loops like if/switch/for
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting limit
nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

# Naming rules for identifiers (variable names, constant names, etc.)
identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - URL
    - x
    - y
    - i
    - to
    - at
    - of
    - from
    - with

# Switch case alignment - match with SwiftFormat
switch_case_alignment:
  indented_cases: true

#-------------------------------------------------------------------
# Output Settings
#-------------------------------------------------------------------
reporter: "emoji"
