# mint run xcodegen generate

name: TemplateApp
options:
  bundleIdPrefix: com.example
  createIntermediateGroups: true
  defaultConfig: Debug
  
settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
  IPHONEOS_DEPLOYMENT_TARGET: 15.0
  SWIFT_VERSION: 5.0

configs:
  Debug: debug
  Release: release

targets:
  TemplateApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - TemplateApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.templateapp
      INFOPLIST_FILE: TemplateApp/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      DEVELOPMENT_ASSET_PATHS: TemplateApp/Resources

  TemplateAppTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - TemplateAppTests
    dependencies:
      - target: TemplateApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.templateapp.tests
      INFOPLIST_FILE: TemplateAppTests/Info.plist

  TemplateAppUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - TemplateAppUITests
    dependencies:
      - target: TemplateApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.templateapp.uitests
      INFOPLIST_FILE: TemplateAppUITests/Info.plist

schemes:
  TemplateApp:
    build:
      targets:
        TemplateApp: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - TemplateAppTests
        - TemplateAppUITests
    archive:
      config: Release

  TemplateAppTests:
    build:
      targets:
        TemplateAppTests: all
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - TemplateAppTests

  TemplateAppUITests:
    build:
      targets:
        TemplateAppUITests: all
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - TemplateAppUITests

