name: Build Unsigned Archive

on:
  workflow_call:

jobs:
  archive:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Mint packages
        uses: actions/cache@v4
        id: cache-mint-packages
        with:
          path: ${{ github.workspace }}/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Generate Xcode Project
        run: mint run xcodegen generate

      - name: Build Unsigned Archive
        run: |
          make build-release
          mkdir -p ci-outputs/production/archives
          cp -R build/archives/TemplateApp.xcarchive ci-outputs/production/archives/

      - name: Verify Archive Contents
        run: |
          set -euo pipefail
          echo "Checking archive contents..."
          # Check if the specific .app directory exists within the archive's Products/Applications path
          ARCHIVE_APP_PATH="./ci-outputs/production/archives/TemplateApp.xcarchive/Products/Applications/TemplateApp.app"
          if [ ! -d "$ARCHIVE_APP_PATH" ]; then
            echo "Error: 'TemplateApp.app' not found in expected archive location ($ARCHIVE_APP_PATH)."
            # Optionally list contents again on error
            echo "--- Archive Contents (on error) ---"
            ls -lR ./ci-outputs/production/archives/TemplateApp.xcarchive || echo "Archive directory not found or empty."
            exit 1
          fi
          echo "✅ Archive content verified."

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-archive
          path: |-
            ./ci-outputs/production/archives/TemplateApp.xcarchive
          retention-days: 3
