name: Build Unsigned Archive

on:
  workflow_call:

jobs:
  archive:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Mint packages
        uses: actions/cache@v4
        id: cache-mint-packages
        with:
          path: ${{ github.workspace }}/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Generate Xcode Project
        run: mint run xcodegen generate

      - name: Build Unsigned Archive
        run: make archive

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-archive
          path: build/archives/TemplateApp.xcarchive
          retention-days: 3
