name: Template App CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-linters:
    name: Run Linters
    uses: ./.github/workflows/run-linters.yml
    
  build-and-test:
    name: Run Tests
    uses: ./.github/workflows/run-tests.yml
    
  release-build:
    name: Build Unsigned Release
    uses: ./.github/workflows/build-unsigned-release.yml
    secrets:
      TEAM_ID: ${{ secrets.TEAM_ID }}
      APPLE_ID: ${{ secrets.APPLE_ID }}