name: Run Tests

on:
  workflow_call:

jobs:
  build-for-testing:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    steps:
      - uses: actions/checkout@v4

      - name: Cache Mint packages
        uses: actions/cache@v4
        id: cache-mint-packages
        with:
          path: ${{ github.workspace }}/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Generate Xcode Project
        run: mint run xcodegen generate

      - name: Build for Testing
        run: |
          make build-test
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-products
          path: build/test-results/DerivedData/Build/Products/
          retention-days: 3

  unit-test:
    runs-on: macos-latest
    needs: build-for-testing
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    outputs:
      result: ${{ steps.unit_tests.outcome }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Mint packages
        uses: actions/cache@v4
        id: cache-mint-packages
        with:
          path: ${{ github.workspace }}/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
          
      - name: Generate Xcode Project
        run: mint run xcodegen generate

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-products
          path: build/test-results/DerivedData/Build/Products/

      - name: Run Unit Tests
        id: unit_tests
        run: |
          make unit-test-without-building

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: build/test-results/unit/TestResults.xcresult
          retention-days: 3

  ui-test:
    runs-on: macos-latest
    needs: build-for-testing
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    outputs:
      result: ${{ steps.ui_tests.outcome }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Mint packages
        uses: actions/cache@v4
        id: cache-mint-packages
        with:
          path: ${{ github.workspace }}/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Generate Xcode Project
        run: mint run xcodegen generate

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-products
          path: build/test-results/DerivedData/Build/Products/

      - name: Run UI Tests
        id: ui_tests
        run: |
          make ui-test-without-building

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: build/test-results/ui/TestResults.xcresult
          retention-days: 3
